# no circle com o 2.0, se usa o arquivo config.yml.

# no config.yml definimos todos os passos a serem executados no circle

version: 2
jobs:
  build:
    working_directory: ~/docker-ci-cd
    docker:
      - image: circleci/python:3
    steps:
      - checkout
      - run:
          name: setup Heroku
          command: bash .circleci/setup-heroku.sh
      - run: python -m unittest
      - setup_remote_docker
      - deploy:
          name: Deploy Master to Heroku
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker build -t docker-ci-cd .
              docker login -u $HEROKU_LOGIN -p $HEROKU_API_KEY registry.heroku.com
              docker tag docker-ci-cd:latest registry.heroku.com/docker-ci-cd/web
              docker push registry.heroku.com/docker-ci-cd/web
            fi

